name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  build_deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build
      uses: peaceiris/actions-hugo@v0.57.2
    - name: deploy
      uses: SamKirkland/FTP-Deploy-Action@1.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        LOCAL_DIR: ./public
      if: success()
