name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  build_deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build
      uses: peaceiris/actions-hugo@v0.57.2
    - name: deploy
      uses: SamKirkland/FTP-Deploy-Action@1.0.0
      env:
        FTP_SERVER: ftp.gapura.my.id
        FTP_USERNAME: ngadimin@gapura.my.id
        FTP_PASSWORD: 1ikhlash1@#..
        LOCAL_DIR: ./public
      if: success()
